### ISSUE TITLE
Ack plugin broken in Linux

### ISSUE THREAD

**Issue by RobertAudi** [carlhuda/janus#117]
Whenever I try to use ack in Linux with the command `:Ack <search-term>` I get an error saying that the ack command is not found. That is because ack is actually called `ack-grep` in linux (or at least in debian-based linux distros). I tried aliasing ack to ack-grep but that did not solve the problem.

**Comment by Globik** [comment]
Also can't execute janus command on linux machine. Why? Chmod 7777 and nothing.
I am in /opt/janus/bin
