### ISSUE TITLE
Error for CtrlP

### ISSUE THREAD

**Issue by czhiling** [carlhuda/janus#363]
Dear developers:

After upgrade to latest janus for MacVim on my mac os lion, I always got error messages when I press Ctrl-P for first time after macvim startup as following:

Error detected while processing function ctrlp#init..<SNR>103_SetLines..<SNR>103_Files..<SNR>103_GlobPath..<SNR>103_GlobPath..<SNR>103_GlobPath..<SNR>103_GlobPath:
line    1:
E219: Missing {.

I do not get any error message if I do ctrl-p on command line vim. 

Would you please give me any hints on how to solve this problem?

**Comment by pmorch** [comment]
@eMxyzptlk, it seems that @czhiling has not responded after two requests for more info. I therefore suggest closing this issue.

**Comment by czhiling** [comment]
Sorry for long silence. 

I would like to report that the issue has disappeared after upgrading.
