### ISSUE TITLE
NERDTree mirror mode by default

### ISSUE THREAD

**Issue by technosophos** [carlhuda/janus#382]
When opening a new tab, and then using `<leader>n`, NERDTree opens with `:NERDTreeToggle`. This shows the directory structure in its original state, not in the same state as the NERDTree on the other tab.

I don't know whether this is generally preferable or not, but it seems to me that the most expected behavior (when compared with other editors) would be to use `:NERDTreeMirror` to keep all of the NERDTrees in sync.

I've been testing this as a way of accomplishing it:

```
map <silent> <leader>n :NERDTreeToggle<CR> :NERDTreeMirror<CR>
```

This seems to work well in cases where one is using multiple tabs. I thought I would suggest that it be made the default configuration for Janus.

**Comment by olleromo** [comment]
-1

**Comment by arithran** [comment]
+!

**Comment by arithran** [comment]
+1
