### ISSUE TITLE
Poor performance after upgrading

### ISSUE THREAD

**Issue by loganlinn** [carlhuda/janus#396]
I recently upgraded my version of janus and have been noticing some sluggishness when switching buffers/tabs, especially when I've had mvim open for a while. At times it takes 3-5 seconds to switch to reasonably sized buffers.

Ive been trying disabling various plugins. Noticed some speedup after disabling syntastic, but it's still not same feel as it was prior to upgrade.

Running MacVim 7.3 (snapshot 64) on a more than capable Macbook Pro.

Is anyone else experiencing this type of performance degradation? Any particular plugins I should try disabling next?

Thanks

__Edit:__ The issues are likely due to having css-color plugin enabled and/or fugitive plugin's git information in the statusline.

**Comment by jarinudom** [comment]
I was getting frequent slowdowns (affecting the whole system, even), and I think I've narrowed it down to some kind of Ruby documentation tooltips popping up when hovering on keywords. I think I've fixed it by setting `set noballooneval` in `~/.gvimrc.after` (not 100% certain, but it seems to be working so far).

**Comment by ap** [comment]
This issue was originally about slowdowns caused by old version of vim-css-color, which are long since fixed. Can this issue be closed, please?

**Comment by ap** [comment]
Thanks!
