### ISSUE TITLE
Auto-update CtrlP cache when a file is written

### ISSUE THREAD

**Issue by thegrubbsian** [carlhuda/janus#403]
It would be super nice if CtrlP would be auto updated when files were written.  Or at least, let us know how to manually do this.  The default <F5> behavior of CtrlP (which is to purge the cache and rebuild) seems to be overwritten in Janus by Gundo.  Anyway, some solution to this be it manual or automatic would be appreciated.

Thanks,
// JC

**Comment by vanderhoop** [comment]
@stephenmckinney Thanks so much!
@galtenberg +1
