### ISSUE TITLE
Unable to override packaged plugin

### ISSUE THREAD

**Issue by johnhampton** [carlhuda/janus#500]
I'm attempting to replace the ZoomWin plugin that is bundled with janus with a newer version. From my understanding of the customization instructions, this should be possible by installing the replacement plugin into .janus. So I should be able to override ZoomWin by installing the replacement version into `~/.janus/zoomwin`.

After following these instructions, the old plugin is still being loaded. I verified that the new plugin is installed correctly by blowing away the old plugin's directory temporarily. The newer version then loads correctly.

Looking at the ZoomWin plugin source code, there is a trap to prevent it from being loaded more than once. From the observed behavior, I would assume that the plugins in .janus are loaded after the packaged plugins? If this is the case, how would I should I override this plugin?

**Comment by trodrigues** [comment]
Issue #603 might be relevant here.

**Comment by eMxyzptlk** [comment]
Closing this one as it's resolved.
