### ISSUE TITLE
Markdown textwidth

### ISSUE THREAD

**Issue by onemanstartup** [carlhuda/janus#527]
at  `~/.vim/janus/vim/core/before/plugin/filetypes.vim`

`au FileType markdown call s:setupWrapping()`

calling globally this settings
`set wrap
   set linebreak
   set textwidth=72
   set nolist
`

so after opening markdown file i stumble with textwidth=72 everywhere until i close macvim.

**Comment by dessalines** [comment]
This textwidth should be removed completely from markdown. Nowhere have I ever heard of a markdown file using a fixed text width. This in fact breaks up viewability with most markdown editors.
