### ISSUE TITLE
Proposal: use Airline

### ISSUE THREAD

**Issue by trevrosen** [carlhuda/janus#557]
I propose we level up the default status line in Janus to use Airline -- https://github.com/bling/vim-airline. It's got colors!

Unlike heavier status bars like Powerline, Airline has no external deps -- pure Vim script. I've been using it in my personal Janus config for awhile and it's been great.

2 questions I wanted to ask before making a PR:

1. Is Janus ok w/ a hard dep on Vim >= 7.2?
2. Does the Janus project have any reason for having not doing a "richer" status bar so far (e.g. lotsnlots of opinionated Poweline users)?

Thanks for your consideration!

**Comment by gad2103** [comment]
@trevrosen can you share your .vimrc.after in a gist? i'm trying to get airline working. what i want is to have buffer tabs so that i can see what buffers i have open in my right pane (next to nerdtree). thanks!

**Comment by trevrosen** [comment]
@gad2103 here's my after file but not sure it will be useful to you, as I don't do anything wrt Airline there: 
https://github.com/trevrosen/Janus-config/blob/master/gvimrc.after

I actually forgot this issue was open and at this point tend to agree with @andrewhood125 anyway, so I'm closing.

**Comment by trevrosen** [comment]
@gad2103 I really only use Janus for Go now and am usually in IDEs w/ Vim support other times, so I can’t claim to know that much about Vim config, tbh. Sorry I can’t be more help.

**Comment by gad2103** [comment]
Thanks for your reply. I'll keep looking for where Janus sets that option...
