### ISSUE TITLE
VIM hang for around 2 seconsd or more when ever I save the file

### ISSUE THREAD

**Issue by phuongnd08** [carlhuda/janus#564]
The file is not big, just 9kB. It's a scss file but the symptom happen to haml file as well. That's really annoying. Any suggestion?

**Comment by westonplatter** [comment]
I wish this info was in the readme

**Comment by lcd047** [comment]
@westonplatter I wish plugin collections like `janus` and `spf-13` wouldn't enable `syntastic` by default.  You really aren't supposed to run it unconfigured, it's a huge resource waster.

**Comment by westonplatter** [comment]
@lcd047 I hear you. If it was configured, what default configurations would you suggest? I don't know a ton about either tool (this project and syntastic) so I'm asking to gain info to create a default config PR.

**Comment by kalbasit** [comment]
@lcd047 please feel free to make an argument in a PR :) that helps everyone using Janus.
