### ISSUE TITLE
Is it possible to add file templates?

### ISSUE THREAD

**Issue by variable** [carlhuda/janus#599]
eg. for new python files, I would like to add the following to the top of new files

```
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import
```

**Comment by wadestuart** [comment]
I do something like this:  https://noahfrederick.com/log/vim-templates-with-ultisnips-and-projectionist/

**Comment by kalbasit** [comment]
@variable please re-open if @wadestuart 's advice is not sufficient.
