### ISSUE TITLE
disable default opening to just a single buffer with nerdtree

### ISSUE THREAD

**Issue by gad2103** [carlhuda/janus#600]
hi there! i'm really loving most of the features in Janus, but I'm getting frustrated with one thing. i know its "wrong" but i usually use tabs for individual buffers so i can tab between files. my first tab is always nerdtree and then i open files using Shift + t in new tabs.

Janus opens nerdtree and an empty buffer by default. can i disable this behavior so that i just get nerdtree without the split window/buffer on the right situation? 

please let me know! thanks!

**Comment by montalvomiguelo** [comment]
I also want to disable that behaviour

**Comment by kalbasit** [comment]
Not sure if this is doable, @scrooloose thoughts?

**Comment by scrooloose** [comment]
I dont use Janus, but I looked briefly at the code.

Looks like this is the line in question: https://github.com/carlhuda/janus/blob/master/janus/vim/tools/janus/after/plugin/nerdtree.vim#L8

Id try commenting that line out first and then trying `vim /my/dir` and see if it behaves as desired.

I'm not sure how Janus does its sourcing ... but if you can load a file after that file above, but before the actual `vimenter` event fires, then you could run something like

```viml
autocmd! AuNERDTreeCmd Vimenter *
```

to prevent the tree from opening - without having to patch Janus.

**Comment by kalbasit** [comment]
Thanks @scrooloose. @montalvomiguelo / @gad2103 please re-open if this does not solve your problem.
