### ISSUE TITLE
Pattern not found error when you toggle nerdtree with Leader+n

### ISSUE THREAD

**Issue by elizar** [carlhuda/janus#601]
This is the exact message:

E486: Pattern Not found: NerdTreeMirror

**Comment by TSiege** [comment]
I have the same error, but it reads `E486: Pattern Not found: submit`.  This happens to me sporadically; sometimes `Leader+n` works and sometimes it doesn't.  I have a feeling it might have to do with multiple plugins mapping functionality to the Leader+n, but I'm not certain.
