### ISSUE TITLE
syntax error near unexpected token `newline' on Fedora release 21

### ISSUE THREAD

**Issue by vmcilwain** [carlhuda/janus#605]
Hello,

I am attempting to get Janus installed on my new installation of Fedora 21 and not having much luck. The current error I am getting is:

[vmcilwain@localhost Desktop]$ curl -Lo- https://bit.ly/janus-bootstrap | bash
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'

I am curious how I can get this installation to work or if Fedora is supported for this. I do have vim and gvim installed. Is there other requirements that I missed?

**Comment by andrewhood125** [comment]
@vmcilwain you shouldn't be getting `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">` back from `curl -Lo- https://bit.ly/janus-bootstrap`. It sounds like you're getting a bad response from curl and that is being piped into bash. 

What is the output if you just run `curl -Lo- https://bit.ly/janus-bootstrap`?

**Comment by vmcilwain** [comment]
@andrewhood125 thanks for the response. Here is what I have from the curl command you sent:

[vmcilwain@localhost ~]$ curl -Lo- https://bit.ly/janus-bootstrap
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Host name provided via SNI and via HTTP are different</p>
</body></html>

**Comment by eMxyzptlk** [comment]
Interesting, I am not getting that problem, perhaps it was an intermittent problem at bit.ly? What's the output of `curl -D- https://bit.ly/janus-bootstrap`

**Comment by vmcilwain** [comment]
@eMxyzptlk Thanks for the response. Here is my output from the curl command you sent:

[vmcilwain@localhost ~]$ curl -D- https://bit.ly/janus-bootstrap
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 28 Jan 2015 18:06:28 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 149
Connection: keep-alive
Cache-Control: private, max-age=90
Location: https://raw.github.com/carlhuda/janus/master/bootstrap.sh
Mime-Version: 1.0
Set-Cookie: _bit=54c92524-000ca-04d0b-251cf10a;domain=.bit.ly;expires=Mon Jul 27 18:06:28 2015;path=/; HttpOnly

<html>
<head>
<title>bit.ly</title>
</head>
<body>
<a href="https://raw.github.com/carlhuda/janus/master/bootstrap.sh">moved here</a>
</body>

**Comment by andrewhood125** [comment]
@vmcilwain that is what it should be outputting. I'm not sure why you are getting the 400 error but to get you up and running you just need to run `bootstrap.sh` 

Paste the contents of https://raw.githubusercontent.com/carlhuda/janus/master/bootstrap.sh into a temp file. Then run `bash temp_file`.

**Comment by vmcilwain** [comment]
@andrewhood125 that got me up and running. I appreciate the help with this.

**Comment by andrewhood125** [comment]
@vmcilwain good to hear! Happy vimming.

**Comment by pekeler** [comment]
Same problem today on OS X 10.10

**Comment by pekeler** [comment]
and the workaround breaks at
```
****************************************
*        Installing watchtower         *
****************************************

rake aborted!
OpenURI::HTTPError: 503 Service Unavailable
/Users/pekeler/.vim/janus/ruby/janus/plugins.rb:51:in `download_and_save_file'
/Users/pekeler/.vim/janus/vim/tools/tasks/watchtower.rake:2:in `block in <top (required)>'
/Users/pekeler/.vim/janus/ruby/janus/plugins.rb:91:in `block (2 levels) in define_install_plugin_tasks'
Tasks: TOP => install => watchtower:install
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake install...]
/Users/pekeler/.vim/Rakefile:76:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
Rake failed.
```

**Comment by eMxyzptlk** [comment]
removed watch_tower in 3f3ccd5faaa92434feb28d7f8a6e96593730b21d

**Comment by vmcilwain** [comment]
FYI - This issue has happened on Centos 7.

Here is the output using curl -D- https://bit.ly/janus-bootstrap

[deploy@localhost apps]$ curl -D- https://bit.ly/janus-bootstrap
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 13 Apr 2015 17:03:30 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 144
Connection: keep-alive
Cache-Control: private, max-age=90
Location: https://raw.github.com/carlhuda/janus/master/bootstrap.sh
Mime-Version: 1.0
Set-Cookie: _bit=552bf6e2-00050-023dc-2e1cf10a;domain=.bit.ly;expires=Sat Oct 10 17:03:30 2015;path=/; HttpOnly

<html>
<head><title>Bitly</title></head>
<body><a href="https://raw.github.com/carlhuda/janus/master/bootstrap.sh">moved here</a></body>
</html>
