### ISSUE TITLE
vi exits 1 with default configuration

### ISSUE THREAD

**Issue by Fryguy** [carlhuda/janus#608]
I have not made any changes to my environment.  I just did an install, and ran vi.  I noticed because `git commit` simply fails to work giving:

```
error: There was a problem with the editor 'vi'.
Please supply the message using either -m or -F option.
```

Related to #519, but I don't have any customization.

**Comment by andrewhood125** [comment]
````
# andrewhood125 at Andrews-MBP in ~ [16:10:18]
$ vim

# andrewhood125 at Andrews-MBP in ~ [16:10:23]
$ echo $?
0

# andrewhood125 at Andrews-MBP in ~ [16:10:25]
$ vi

# andrewhood125 at Andrews-MBP in ~ [16:10:28]
$ echo $?
1
````

Hmm...

**Comment by Fryguy** [comment]
So, I changed my default EDITOR and VISUAL to vim and it works, so that's good.  I still think it's a bug though, but I guess with a workaround it's ok.

**Comment by eMxyzptlk** [comment]
Usually Vim starts in a vi compatible mode when the executable is 'vi'. Worse, I believe that if you have 'vi' installed, it will crash because it does not recognize Vim settings. I always have in my environment `alias vi=vim`.
