### ISSUE TITLE
ctrlp ignore for bower / npm / ember cache directories

### ISSUE THREAD

**Issue by dukedave** [carlhuda/janus#611]
Would a pull be accepted to add `bower_components`, `node_modules`, and `tmp` (used by Ember) to `g:ctrlp_custom_ignore`, [here](https://github.com/carlhuda/janus/blob/master/janus/vim/tools/janus/after/plugin/ctrlp.vim)? Without these ignored ctrlp's performance makes it unusable.

I see at least one accepted pull (#541) for this kind of thing, but I'm not sure if there are any guidelines on what is/isn't considered within the scope of Janus?

If this doesn't qualify for a pull, then I would propose it should be documented, including an example of adding these to `.vimrc.after`.

**Comment by simonweil** [comment]
:+1:

**Comment by wycats** [comment]
It might be nicer to just include https://github.com/vim-scripts/gitignore.git. I recently added this to my custom `janus` directory to great success.

@eMxyzptlk thoughts?

**Comment by eMxyzptlk** [comment]
@wycats do you experience any slowdown? I am not opposed to the convenience that it might bring, but I am a bit reluctant to the idea of another I/O from Janus.

I'll give it a try myself as well.

**Comment by eMxyzptlk** [comment]
@wycats It didn't work well with me, somehow my project's `.gitignore` ended up in an empty CtrlP. I'll ignore `bower_component` and `node_modules` instead.

**Comment by dolohow** [comment]
Create PR for that? :)

**Comment by kalbasit** [comment]
@dolohow sure and please feel free to create PRs as you see fit.

**Comment by alvincrespo** [comment]
Just in case anyone comes across this PR - this seems to work for me:

**~/.vimrc.after**
```
set wildignore+=*/tmp/*,*.o,*.so,*.swp,*.zip,*/node_modules/*,*/bower_components/*
```

**Comment by indiesquidge** [comment]
@alvincrespo thanks for that!

**Comment by dxuehu** [comment]
it would've been nice to just add the wildignore to vimrc.after! i needed the node_modules lookup.

**Comment by dolohow** [comment]
Just use grep

**Comment by johnromani90** [comment]
@alvincrespo works for me

**Comment by AdamT** [comment]
Not sure if I should open an issue or perhaps I'm doing something wrong. I've recently set up a new dev machine (macOS 10.13.1) and recently installed Janus with macvim (via homebrew), nothing special. I'm noticing that ctrlp is not ignoring `/tmp/cache/assets/sprockets/etc... .cache`

In my
.vimrc.after I have:
```
set wildignore+=*/elm-stuff*,*/tmp/*,*.swp,*.zip,*.cache
```

I'm also refreshing the cache with F5 (on this lovely 🙄 touchbar)

Should I file an issue or is it something on my end?
