### ISSUE TITLE
During opening of a file, pressing enter will move the current line down

### ISSUE THREAD

**Issue by amcpherson** [carlhuda/janus#612]
If i open a file:

```
vi foo
```

and before seeing the file press enter, the current line (the line the cursor was last on when the file was previously opened) moves down 1 line.  Of course when the file is fully opened, pressing enter just moves the cursor.

Reproduced on a linux and a mac build.

**Comment by eMxyzptlk** [comment]
Do you experience the same without Janus?

**Comment by amcpherson** [comment]
No.  One difference is it takes vim longer to start up with janus installed, likely because of the plugins.  I am wondering if during loading of the plugins it enters some state that changes the meaning of <enter>.  After the file has fully loaded, i can undo, and each undo moves the altered line back up one line, until the altered line is back to where it was before.

**Comment by dolohow** [comment]
I think it should be closed cause it is unrelated to janus project.
