### ISSUE TITLE
Narrow region plugin slows down leader command for NERDTree

### ISSUE THREAD

**Issue by DanS** [carlhuda/janus#620]
I'm not sure what changed but a while ago opening/closing NERDTree with `<leader>n` became much slower.

Yesterday I tracked this down.  The narrow region plugin defines a leader command `<leader>nr`.  When that isn't there Vim can react to the `<leader>n` command as soon as the "n" is typed.  With the narrow region command there Vim waits a while after `<leader>n` is typed to see if you will type an "r".  

I've started avoiding this issue by adding:
  `nunmap <leader>nr`
to my gvimrc.after.  This works for me because I use `<leader>n` all the time, and I never use `<leader>nr`.

I think Janus could be improved by providing a solution to this "out of the box" so that the NERDTree `<leader>n` command responds without delay.  My suggestion would be to map 'narrow region' to a leader command that does not start with 'n'.

**Comment by dolohow** [comment]
Do you want me to create a PR for that? :)

**Comment by kalbasit** [comment]
Sure, what mapping you propose for narrow region?

**Comment by dolohow** [comment]
Maybe <leader>mr ?

**Comment by kalbasit** [comment]
or `<leader>rn` perhaps ?

**Comment by dolohow** [comment]
Ok, then ;)
