### ISSUE TITLE
Unable to find gotags

### ISSUE THREAD

**Issue by alvincrespo** [carlhuda/janus#629]
Just updated janus and I'm getting this error when trying to open up a golang file:

```
vim-go: could not find 'gotags'. Run :GoInstallBinaries to fix it.
Press ENTER or type command to continue
```

When I try to run :GoInstallBinaries, I get the following error:

`vim.go hg(mercurial) executable not found`

**Comment by kalbasit** [comment]
Install mercurial and it should work.
