### ISSUE TITLE
Emmet?

### ISSUE THREAD

**Issue by andysaini** [carlhuda/janus#630]
Hi, how do I integrate emmet with janus?

**Comment by Lucasosf** [comment]
@andysaini I think you have to use the https://github.com/mattn/emmet-vim .
There are some instructions of how to add plugins in the customization area in the janus readme: https://github.com/carlhuda/janus#customization

It helped you?

**Comment by andysaini** [comment]
@Lucasosf I've installed emmet by cloning it into my .janus directory, but it(?) carries out some false completions. For ex if I press <tab> after writing say, andy, it'll complete it to <andy>_</andy>(underscore depicts cursor position). I think it's conflicting with the snipmate snippets already in place..

**Comment by andysaini** [comment]
Tried removing and re-installing emmet, now it has stopped working altogether.

**Comment by kalbasit** [comment]
Try disabling snipmate, perhaps they are not intended to work together.

**Comment by andysaini** [comment]
Hmm, closing this, for now!
