### ISSUE TITLE
customising <leader>ul

### ISSUE THREAD

**Issue by eQu1NoX** [carlhuda/janus#631]
Hi,

How could I customise the pattern inserted as a line below/above the current line, when pressing <leader>ul ? Would this be trivial to do?

Thanks

**Comment by kalbasit** [comment]
`<leader>ul` is defined [here](https://github.com/carlhuda/janus/blob/049be5eefe5c3e77ec331ce7c4b6201e412e9f70/janus/vim/core/before/plugin/mappings.vim#L37) you can copy/paste it to your `~/.vimrc.after` and change it to your liking.
