### ISSUE TITLE
neovim breaking changes

### ISSUE THREAD

**Issue by dolohow** [carlhuda/janus#633]
As stated in https://github.com/neovim/neovim/wiki/Following-HEAD
"The 'encoding' option can no longer be changed after initialization."

When starting nvim I have
```
Error detected while processing /home/MY_USERNAME/.vim/janus/vim/core/before/plugin/settings.vim:
line    9:
E905: Cannot set this option after startup: encoding=utf-8
```

**Comment by simonweil** [comment]
As nvim sets the encoding by default to utf-8
the encoding configuration should be within a `if !has('nvim')`.

**Comment by dolohow** [comment]
You want me to create a pull request for that?

**Comment by kalbasit** [comment]
@dolohow yes please.

**Comment by rafaelrinaldi** [comment]
@kalbasit FYI I'm seeing the exact same message (about utf8 encoding) whenever I `:source ~/.vimrc`.

**Comment by dolohow** [comment]
Update your janus.
