### ISSUE TITLE
Cannot set linespace in vim

### ISSUE THREAD

**Issue by jaywolff** [carlhuda/janus#635]
changing "set linespace=5" in the ~/.vimrc.after file has no effect. Tested on two fresh installs of janus on 2 Arch Linux machines. Neither does running ":set linespace=5" from within command mode in vim.

Heres a link to my .vimrc.after
http://pastebin.com/9i9jsMdV

**Comment by kalbasit** [comment]
linespace works only in the GUI (Gvim, MacVim etc...), it does not work in
terminal vim.
