### ISSUE TITLE
E117: Unknown function: netrw#NetrwBrowseX

### ISSUE THREAD

**Issue by dukedave** [carlhuda/janus#640]
With a plain install of Janus on the `vim` which comes with Ubuntu 14.04.

The `:Gbrowse` fugitive command *inside a commit* (i.e. first `:Gblame` then `o` a commit), causes:

```
E117: Unknown function: netrw#NetrwBrowseX                                                                                                    
Press ENTER or type command to continue 
```

There seems to be a related issue here, but it was fixed back in February: tpope/vim-fugitive#594

**Comment by kalbasit** [comment]
I just updated all submodule, can you pull and try again? If it didn't work then it's possibly an issue in Fugitive itself.

**Comment by dukedave** [comment]
@kalbasit that fixed it, thanks :+1:
