### ISSUE TITLE
[Feature] Add class names at class 'end' keywords

### ISSUE THREAD

**Issue by BartlomiejSkwira** [carlhuda/janus#641]
When I type in `class Klass` and hit enter button I get an `end` keyword added automatically, the result is:
```
class Klass
end
```
Would it be possible to have commented-out class/module/method names automatically added behind `end` keywords?
```
module Module
  class Superclass
    class Subclass
    end # class Subclass
  end # class Superclass
end # module Module
```

**Comment by kalbasit** [comment]
This I believe is coming from the [endwise plugin](https://github.com/tpope/vim-endwise). You should probably ask there.

**Comment by BartlomiejSkwira** [comment]
@kalbasit you're right, thanks!
