### ISSUE TITLE
Rails colors

### ISSUE THREAD

**Issue by JonErikDSuero** [carlhuda/janus#643]
Sometimes, I lose the colors when I try switching files through ZoomWin, BufferGator, or CtrlP. Then, when I try changing file again using BufferGator, I get this error:

```
Error detected while processing function rails#buffer_setup:
line   73:
E666: compiler not supported: rails
```

I do have this file: `.vim/janus/vim/langs/rails/compiler/rails.vim`
I used `brew install macvim --with-override-system-vim` to install `macvim`. This is my vim's version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  8 2015 16:08:40)
MacOS X (unix) version
Included patches: 1-936
Compiled by Homebrew
```

Once I lose the colors on a file, the next opened files also have no colors. I have to restart vim to get colors again.

Do you guys have some ideas how to fix this?

Thanks

**Comment by rodrei** [comment]
I'm having the same issue. I'm on MacVim 7.4 as too.

**Comment by JonErikDSuero** [comment]
no answer
