### ISSUE TITLE
How to disable hiding of quotation marks in JSON files?

### ISSUE THREAD

**Issue by mlncn** [carlhuda/janus#655]
Apologies for the support request, but i really want to disable this Janus feature of autohiding of quotes around text in JSON files and cannot figure out how.  Thanks!

**Comment by kalbasit** [comment]
This is provided by the [json plugin](https://github.com/elzr/vim-json) located [here](https://github.com/elzr/vim-json). Please follow the [Disabling a plugin wiki page](https://github.com/carlhuda/janus/wiki/Customization#disabling-a-plugin) to disable this plugin.

**Comment by mlncn** [comment]
Awesome thank you!!

`let g:vim_json_syntax_conceal = 0`

In ~/.vimrc.after disables just the hidden quote marks, and keeps the rest of the JSON features.

Should i do a pull request to give that plugin a mention in the features list in the README?  I promise i could have figured this out on my own if i had found a mention of JSON there!

**Comment by kalbasit** [comment]
I'd appreciate that @mlncn thanks.
