### ISSUE TITLE
Update ZoomWin to v25

### ISSUE THREAD

**Issue by chauncey-garrett** [carlhuda/janus#660]
It's available on the author's website at http://www.drchip.org/astronaut/vim/index.html#ZOOMWIN. I've asked him to update the script at http://vim.sourceforge.net/scripts/script.php?script_id=508 as well.

There are several bugfixes included; one of them is for an issue with RestoreUserSettings that I'm currently experiencing.

**Comment by kalbasit** [comment]
I found https://github.com/sh-dude/ZoomWin, you want to file a PR?

**Comment by chauncey-garrett** [comment]
Sure thing!
