### ISSUE TITLE
Use vim-polyglot instead of maintaining a smaller list of langs

### ISSUE THREAD

**Issue by chauncey-garrett** [carlhuda/janus#661]
[vim-polyglot](https://github.com/sheerun/vim-polyglot) is a great collection of language packs for vim.

**Comment by kalbasit** [comment]
wow nice! feel free to file a PR but I'll try to get to it in about a week.

**Comment by andersonvom** [comment]
@kalbasit I believe this should do it

**Comment by kalbasit** [comment]
@andersonvom thanks for the PR, it's merged. Apologies for the very late reply, life got very busy lately.
