### ISSUE TITLE
vim-matchit repo deleted

### ISSUE THREAD

**Issue by cazzerson** [carlhuda/janus#673]
It looks like @edsono has deleted https://github.com/edsono/vim-matchit.git, which Janus depends on.

**Comment by imlcl** [comment]
Yes, I can't install janus now...

**Comment by marcinbiegun** [comment]
There are other repos containing this plugin, e.g. `https://github.com/geoffharcourt/vim-matchit`

I've replaced it in `~/.vim/.gitmodules`, but now the `rake` task fails on:

```
error: no such remote ref ceaf496a3763f3c20bc7f50c2135df4f1775ae05
Fetched in submodule path 'janus/vim/tools/matchit', but it did not contain ceaf496a3763f3c20bc7f50c2135df4f1775ae05. Direct fetching of that commit failed.
```

Anyone knows how to fix it?

**Comment by marcinbiegun** [comment]
I've made a fork, containing `matchit` files, instead of submodule link. If you want to install it, use  `git clone --recursive https://github.com/marcinbiegun/janus.git "${HOME}/.vim"`. Please reinstall it back from original repo, when it's fixed.
