### ISSUE TITLE
vimrc.after does not seem to be honoured

### ISSUE THREAD

**Issue by TimWSpence** [carlhuda/janus#675]
janus doesn't seem to honour my .vimrc.after settings. Looking at janus/vim/vimrc, it looks like the last line should possibly say
```
source ~/.vimrc.after
```
?

**Comment by TimWSpence** [comment]
Problem looks like it could have been introduced with commit 43e6a1ac7feeaf046eca31f5244854f3031f7f57 .

Maybe I'm missing something but it seems to have moved the sourcing functionality to janus/vim/core/after/plugin/vimrc_after.vim b/janus/vim/core/after/plugin/vimrc_after.vim and a quick grep suggested that nothing sources this hence .vimrc.after is never called? Although this was a LONG time ago so I can't really see that that is the problem

**Comment by kalbasit** [comment]
@TimWSpence that path should be loaded automatically, run the command `:set rtp?` to confirm the path is there.
