### ISSUE TITLE
Problem with powerline installed

### ISSUE THREAD

**Issue by jasonpenny** [carlhuda/janus#681]
I have powerline installed and a recent janus update started causing my vim to show lots of errors.

```
E121: Undefined variable: #warningmsg#
E15: Invalid expression: pyeval('powerline.new_window()')%#warningmsg#%{SyntasticStatuslineFlag()}%*
...
```

from https://github.com/carlhuda/janus/blob/922d3848f0dc3aae6b0c43492dc29cd4fd448b6a/janus/vim/tools/janus/after/plugin/syntastic.vim#L2-L8

This change seems to stop the errors:
```
-  if globpath(&runtimepath, 'plugin/airline.vim', 1) ==# '' && globpath(&runtimepath, 'plugin/lightline.vim', 1) ==# ''
+  if globpath(&runtimepath, 'plugin/airline.vim', 1) ==# '' && globpath(&runtimepath, 'plugin/lightline.vim', 1) ==# '' && globpath(&runtimepath, 'plugin/powerline.vim', 1) ==#
```

but it also seems that syntastic is now set to passive by default (so it no longer checks syntax on file save)

was that on purpose?

**Comment by kalbasit** [comment]
The change of setting Syntastic to passive mode was done in #679. Please file a PR to fix the issue that you are experiencing.
