### ISSUE TITLE
Some fugitive commands fail with vim 8 and current submodule version

### ISSUE THREAD

**Issue by thisgeek** [carlhuda/janus#698]
Some fugitive commands used with [Vim 8 break because of a check for ':terminal'](https://github.com/tpope/vim-fugitive/issues/928). Fugitive added a fix in 913fff1, but janus currently uses fugitive @ c00ebd7. Updating to 913fff1 resolves by issues.

**Comment by dpandoffx** [comment]
+1

**Comment by kalbasit** [comment]
thanks for letting me know, I've pushed an update to all submodules https://github.com/carlhuda/janus/commit/078048e2c647562851176c2f753f5c36f77a9bd3
