### ISSUE TITLE
pattern not found bindings

### ISSUE THREAD

**Issue by Migacz85** [carlhuda/janus#703]
After installing it, I run first command <leader> n and found this issue. Some suggestions?

**Comment by kalbasit** [comment]
That's not much to go on, unfortunately. Please answers the questions below and include as many details as possible. Thanks!

1. What operating system you're using?
2. What version of Vim you're using?
3. Steps to reproduce.
4. Full error message.

**Comment by kalbasit** [comment]
That's not much to go on.

1. What operating system you're using?
2. What version of Vim you're using?
3. Steps to reproduce.
4. Full error message.

**Comment by Migacz85** [comment]
I decided that I will configure vim by myself and will fight more with configuring `.vimrc`. Maybe it's buggy but is mine and I'm aware of what each line is doing.
