### ISSUE TITLE
Best way to uninstall Janus

### ISSUE THREAD

**Issue by alexventuraio** [carlhuda/janus#705]
Recently I've playing around with some configurations to user ESLint, [ale](https://github.com/dense-analysis/ale) and Prettier to work with Reactjs. But I did some different customizations that I ended up messing up my development environment.

What I want to do is to uninstall Janus completely from my machine so I can start over again customizing it but with a brand new Janus installation.

I've looking for a proper way to do so but I have no luck. Is there kind of an official way to uninstall Janus?

**Comment by andersonvom** [comment]
Just remove the following files/directories:

* `$HOME/.vim`
* `$HOME/.vimrc`
* `$HOME/.vimrc.before` (if present)
* `$HOME/.vimrc.after` (if present)

Instead of removing them, you might want to move them elsewhere, just in case you want it back.

**Comment by andersonvom** [comment]
Just remove the following files/directories:

* `$HOME/.vim`
* `$HOME/.vimrc`
* `$HOME/.vimrc.before` (if present)
* `$HOME/.vimrc.after` (if present)

Instead of removing them, you might want to move them elsewhere, just in case you want it back.

**Comment by alexventuraio** [comment]
@andersonvom Thanks for clarifying!
